# Generated by Django 4.2 on 2025-11-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mas', models.CharField(max_length=50)),
                ('especie_mas', models.CharField(max_length=50)),
                ('raza_mas', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo_mas', models.CharField(blank=True, max_length=10, null=True)),
                ('edad_anios_mas', models.PositiveIntegerField(default=0)),
                ('estado_mas', models.CharField(default='Disponible', max_length=20)),
                ('fecha_ingreso_mas', models.DateField(auto_now_add=True)),
                ('observaciones_mas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_per', models.CharField(max_length=20, unique=True)),
                ('nombres_per', models.CharField(max_length=100)),
                ('apellidos_per', models.CharField(max_length=100)),
                ('correo_per', models.EmailField(max_length=100, unique=True)),
                ('telefono_per', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_per', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro_per', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_ado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud_ado', models.DateField(auto_now_add=True)),
                ('fecha_aprobacion_ado', models.DateField(blank=True, null=True)),
                ('estado_ado', models.CharField(default='Solicitada', max_length=20)),
                ('documento_ado', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='Adopciones.mascota')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='Adopciones.persona')),
            ],
        ),
    ]
